name: TMDB to Blogger
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run
        env:
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          G_CLIENT_ID: ${{ secrets.G_CLIENT_ID }}
          G_CLIENT_SECRET: ${{ secrets.G_CLIENT_SECRET }}
          G_REFRESH_TOKEN: ${{ secrets.G_REFRESH_TOKEN }}
        run: node post.js
