name: TMDB to Blogger
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Script
        env:
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          G_CLIENT_ID: ${{ secrets.G_CLIENT_ID }}
          G_CLIENT_SECRET: ${{ secrets.G_CLIENT_SECRET }}
          G_REFRESH_TOKEN: ${{ secrets.G_REFRESH_TOKEN }}
        run: |
          echo "Checking files..."
          ls -la
          node post.js
